title: Datenstrukturen und KI
author: Michael Brenner
copyright: "2024"
# logo: figures/TUDelft_logo_rgb.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://github.com/embee0/ds-ki" #Replace this with your own URL
  home_page_in_navbar       : true
  extra_footer: |
        <div>
            🤖
        </div>

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - attrs_block
    - attrs_inline # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-attributes-inline
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-attributes-inline
  myst_url_schemes: [ mailto, http, https ]
  myst_dmath_double_inline: true



#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    language: de
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      # home_page_in_toc: true
      repository_url: "https://github.com/embee0/ds-ki" #add your own repo URL here
      use_repository_button: true
      use_issues_button : false
      launch_buttons:
        thebe: true
    html_show_copyright: true  # Evtl ändern?
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - teachbooks_sphinx_tippy

bibtex_bibfiles: 
  - references.bib
